# permissions for end users to edit canaries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: canary-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: canary
    app.kubernetes.io/part-of: canary
    app.kubernetes.io/managed-by: kustomize
  name: canary-editor-role
rules:
- apiGroups:
  - canary.k8shuginn.io
  resources:
  - canaries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - canary.k8shuginn.io
  resources:
  - canaries/status
  verbs:
  - get
