apiVersion: canary.k8shuginn.io/v1alpha1
kind: Canary
metadata:
  labels:
    app.kubernetes.io/name: canary
    app.kubernetes.io/instance: canary-sample
    app.kubernetes.io/part-of: canary
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: canary
  name: canary-sample
spec:
  # TODO(user): Add fields here
