apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: old-deployment
  name: old-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: old-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: old-deployment
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources: {}
status: {}
